# -*- coding: utf-8 -*-
"""
module2.py — Explainability Engine
====================================
Bias-Free Hiring Pipeline — Stage 2

Reads the ranking decisions produced by module1 and transforms raw numeric
scores into structured, human-readable explanations that a hiring manager can
act on immediately — without needing to understand the underlying ML model.

Design philosophy
-----------------
*   **Zero external dependencies.** Pure Python stdlib.  No LLMs, no ML, no
    HTTP calls.  Every sentence is generated by deterministic rule-based
    templates wired to the actual signal values.
*   **Truthfulness over polish.**  Text never flatters or obscures weak scores.
    Labels, verdicts, and recommendations are anchored to concrete thresholds.
*   **Graceful degradation.**  A missing parsed JSON never crashes the engine —
    it generates a leaner explanation from ranking_details alone and flags the
    gap clearly.
*   **Auditability.**  Every output JSON records exactly which data were
    available and which were inferred from defaults, forming a paper trail for
    GDPR audit (Stage 3).

Pipeline position
-----------------
    module0  → anonymized_cvs/Candidate_01.txt
    module0b → parsed/Candidate_01.json
    module1  → ranking_report.txt  +  ranker.last_ranking_details
    module2  → explanations/Candidate_01.json       ← one per candidate
               explanations/summary_report.txt      ← all candidates

Standalone usage
----------------
    python module2.py --ranking-file ranking_details.json \\
                      --parsed-dir parsed \\
                      --output-dir explanations

    # Dump last_ranking_details from a running pipeline for debugging:
    python -c "import json, module1; r = module1.load_ranker(); \\
               json.dump(r.last_ranking_details, open('ranking_details.json','w'), indent=2)"

Programmatic usage (called by main.py)
----------------------------------------
    import module2
    ok = module2.run(
        ranking_details=ranker.last_ranking_details,
        parsed_dir='parsed',
        output_dir='explanations',
    )
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import logging
import math
import os
import re
import sys
import textwrap
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

# ══════════════════════════════════════════════════════════════════════════
# Module-level logger
# ══════════════════════════════════════════════════════════════════════════
logger = logging.getLogger(__name__)

# ══════════════════════════════════════════════════════════════════════════
# Constants — thresholds, labels, formatting
# ══════════════════════════════════════════════════════════════════════════

# ── Verdict thresholds ────────────────────────────────────────────────────
VERDICT_STRONG_THRESHOLD:  float = 0.75
VERDICT_GOOD_THRESHOLD:    float = 0.55
VERDICT_PARTIAL_THRESHOLD: float = 0.40

# ── Score label thresholds ────────────────────────────────────────────────
LABEL_EXCELLENT_THRESHOLD: float = 0.80
LABEL_GOOD_THRESHOLD:      float = 0.60
LABEL_FAIR_THRESHOLD:      float = 0.40

# ── Strengths detection thresholds ────────────────────────────────────────
STRENGTH_KEYWORD_THRESHOLD:    float = 0.70
STRENGTH_SEMANTIC_THRESHOLD:   float = 0.70
STRENGTH_EXPERIENCE_MONTHS:    int   = 24
STRENGTH_QUALITY_THRESHOLD:    float = 0.80
STRENGTH_SENIOR_MONTHS:        int   = 60   # 5 years — triggers "senior" phrasing
STRENGTH_PERFECT_KEYWORD:      float = 1.0  # all JD skills present

# ── Gaps detection thresholds ─────────────────────────────────────────────
GAP_LIMITED_EXPERIENCE_MONTHS: int   = 12
GAP_LOW_KEYWORD_THRESHOLD:     float = 0.30
GAP_LOW_QUALITY_THRESHOLD:     float = 0.50
GAP_MAX_SKILL_ITEMS:           int   = 5    # cap individual skill gap bullets

# ── Advanced degree identifiers (for strength detection) ─────────────────
ADVANCED_DEGREE_LEVELS: frozenset = frozenset({
    "PhD", "M.Sc", "M.A", "MBA", "M.E", "M.Tech", "Master", "MCA",
    "Postgraduate",
})

# ── Formatting ────────────────────────────────────────────────────────────
REPORT_WIDTH:    int = 78   # column width of the summary report
ISO_FMT:         str = "%Y-%m-%dT%H:%M:%S"
HUMAN_DATE_FMT:  str = "%d %B %Y, %H:%M"
OUTPUT_DIR_NAME: str = "explanations"
SUMMARY_FILENAME: str = "summary_report.txt"
LOG_FORMAT:      str = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
DATE_FMT:        str = "%H:%M:%S"


# ══════════════════════════════════════════════════════════════════════════
# Typed intermediate structures
# ══════════════════════════════════════════════════════════════════════════

@dataclasses.dataclass(frozen=True)
class RankingEntry:
    """Immutable snapshot of one candidate's ranking signal from module1.

    All fields correspond directly to keys in ranker.last_ranking_details.
    Defaults guard against missing keys so callers never need try/except.
    """
    candidate_id:    str
    final_score:     float
    semantic_score:  float
    keyword_score:   float
    quality_score:   float
    matched_skills:  Tuple[str, ...]
    missing_skills:  Tuple[str, ...]
    jd_skill_count:  int
    rank:            int

    @classmethod
    def from_dict(cls, candidate_id: str, data: Dict[str, Any]) -> "RankingEntry":
        """Construct a RankingEntry from a raw ranking_details sub-dict.

        Args:
            candidate_id: The candidate's identifier string.
            data:         The raw dict from ranker.last_ranking_details.

        Returns:
            A populated, validated RankingEntry instance.
        """
        return cls(
            candidate_id   = candidate_id,
            final_score    = float(data.get("final_score",    0.0)),
            semantic_score = float(data.get("semantic_score", 0.0)),
            keyword_score  = float(data.get("keyword_score",  0.0)),
            quality_score  = float(data.get("quality_score",  0.5)),
            matched_skills = tuple(data.get("matched_skills", [])),
            missing_skills = tuple(data.get("missing_skills", [])),
            jd_skill_count = int(data.get("jd_skill_count",   0)),
            rank           = int(data.get("rank",              0)),
        )


@dataclasses.dataclass
class ParsedContext:
    """Optional enrichment data loaded from module0b's parsed JSON.

    All fields have safe defaults so downstream code never needs to None-check.
    The ``available`` flag tracks whether a real parsed file was found; it is
    recorded in the output JSON for auditability.
    """
    available:                bool             = False
    total_experience_months:  int              = 0
    roles:                    List[Dict[str, Any]] = dataclasses.field(default_factory=list)
    education:                List[Dict[str, Any]] = dataclasses.field(default_factory=list)
    certifications:           List[str]        = dataclasses.field(default_factory=list)
    languages:                List[str]        = dataclasses.field(default_factory=list)
    parse_warnings:           List[str]        = dataclasses.field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ParsedContext":
        """Construct a ParsedContext from a module0b parsed JSON dict.

        Args:
            data: Full parsed JSON dict (top-level, not just 'sections').

        Returns:
            A populated ParsedContext with available=True.
        """
        sections = data.get("sections", {})
        return cls(
            available               = True,
            total_experience_months = int(sections.get("total_experience_months", 0)),
            roles                   = list(sections.get("experience", [])),
            education               = list(sections.get("education",  [])),
            certifications          = list(sections.get("certifications", [])),
            languages               = list(sections.get("languages",  [])),
            parse_warnings          = list(data.get("parse_warnings", [])),
        )

    @classmethod
    def unavailable(cls) -> "ParsedContext":
        """Return an empty ParsedContext representing a missing parsed file.

        Returns:
            A ParsedContext with available=False and all fields at defaults.
        """
        return cls(available=False)


@dataclasses.dataclass(frozen=True)
class CandidateContext:
    """Complete merged view of one candidate's data from all pipeline stages.

    Combines the numeric signals from module1 (RankingEntry) with the
    structural data from module0b (ParsedContext) into a single object that
    all downstream functions operate on.
    """
    ranking:  RankingEntry
    parsed:   ParsedContext
    n_candidates: int   # total candidates in this ranking run

    @property
    def candidate_id(self) -> str:
        """Convenience accessor for the candidate's identifier."""
        return self.ranking.candidate_id


# ══════════════════════════════════════════════════════════════════════════
# Verdict & label helpers
# ══════════════════════════════════════════════════════════════════════════

def _verdict(score: float) -> str:
    """Map a final score to its human-readable verdict string.

    Args:
        score: The candidate's final_score (0.0 – 1.0).

    Returns:
        One of: "Strong Match", "Good Match", "Partial Match", "Weak Match".
    """
    if score >= VERDICT_STRONG_THRESHOLD:
        return "Strong Match"
    if score >= VERDICT_GOOD_THRESHOLD:
        return "Good Match"
    if score >= VERDICT_PARTIAL_THRESHOLD:
        return "Partial Match"
    return "Weak Match"


def _score_label(score: float) -> str:
    """Map a numeric score (0–1) to a qualitative label.

    Args:
        score: Any sub-score value (semantic, keyword, quality, final).

    Returns:
        One of: "Excellent", "Good", "Fair", "Poor".
    """
    if score >= LABEL_EXCELLENT_THRESHOLD:
        return "Excellent"
    if score >= LABEL_GOOD_THRESHOLD:
        return "Good"
    if score >= LABEL_FAIR_THRESHOLD:
        return "Fair"
    return "Poor"


def _pct(score: float) -> str:
    """Format a 0–1 score as a percentage string, e.g. 0.75 → '75%'.

    Args:
        score: A value between 0.0 and 1.0.

    Returns:
        Percentage string with no decimal places.
    """
    return f"{round(score * 100)}%"


def _years_months_str(total_months: int) -> str:
    """Express a duration in months as a natural English string.

    Examples:
        0  → "no recorded experience"
        6  → "6 months"
        12 → "1 year"
        18 → "1 year 6 months"
        24 → "2 years"

    Args:
        total_months: Non-negative integer number of months.

    Returns:
        A natural English duration string.
    """
    if total_months <= 0:
        return "no recorded experience"
    years  = total_months // 12
    months = total_months % 12
    if years == 0:
        return f"{months} month{'s' if months != 1 else ''}"
    if months == 0:
        return f"{years} year{'s' if years != 1 else ''}"
    return (
        f"{years} year{'s' if years != 1 else ''} "
        f"{months} month{'s' if months != 1 else ''}"
    )


def _highest_education(education: List[Dict[str, Any]]) -> Tuple[str, str]:
    """Determine the highest education level and field from an education list.

    The ordering of ``_EDU_PRIORITY`` defines which level is considered
    'highest'; the first match wins.

    Args:
        education: List of education entry dicts from module0b.

    Returns:
        Tuple of (level_string, field_string).  Both may be empty strings.
    """
    _EDU_PRIORITY: List[str] = [
        "PhD", "MBA", "M.Tech", "M.Sc", "M.E", "M.A", "MCA", "Master",
        "Postgraduate", "B.Tech", "B.E", "B.Sc", "B.A", "BCA", "Bachelor",
        "Undergraduate", "Diploma", "Certificate", "HSC", "SSLC",
        "High School", "Secondary", "CBSE", "ICSE",
    ]
    if not education:
        return "", ""

    best_level = ""
    best_field = ""
    best_priority = len(_EDU_PRIORITY) + 1   # lower index = higher degree

    for entry in education:
        level = entry.get("level", "")
        field = entry.get("field", "")
        try:
            priority = _EDU_PRIORITY.index(level)
        except ValueError:
            priority = len(_EDU_PRIORITY)

        if priority < best_priority:
            best_priority = priority
            best_level    = level
            best_field    = field

    return best_level, best_field


# ══════════════════════════════════════════════════════════════════════════
# Rule-based text generation
# ══════════════════════════════════════════════════════════════════════════

class TextGenerator:
    """Pure rule-based natural language generator for candidate explanations.

    Every public method accepts a ``CandidateContext`` and returns a string
    or list of strings.  There are no side effects, no I/O, no ML models.
    Template selection is driven by the actual signal values so that the
    output reads differently for strong vs weak candidates.
    """

    # ──────────────────────────────────────────────────────────────────────
    # Headline
    # ──────────────────────────────────────────────────────────────────────

    def headline(self, ctx: CandidateContext) -> str:
        """Generate a one-sentence headline capturing rank, verdict, and key signal.

        The headline is the first thing a hiring manager reads and must
        convey the most important finding immediately.

        Args:
            ctx: Merged candidate context.

        Returns:
            A concise, concrete one-sentence headline string.
        """
        r   = ctx.ranking
        n   = ctx.n_candidates
        v   = _verdict(r.final_score)
        pct = _pct(r.final_score)
        exp = ctx.parsed.total_experience_months

        rank_phrase = (
            f"Ranked #{r.rank} of {n}"
            if n > 1
            else f"Ranked #{r.rank}"
        )

        # Skill summary clause
        if r.jd_skill_count > 0:
            skill_clause = (
                f"{len(r.matched_skills)} of {r.jd_skill_count} required skills matched"
            )
        else:
            skill_clause = "skill overlap assessed"

        # Experience clause
        if exp >= STRENGTH_SENIOR_MONTHS:
            exp_clause = f"{exp // 12}+ years of experience"
        elif exp >= STRENGTH_EXPERIENCE_MONTHS:
            exp_clause = f"{exp // 12} years of relevant experience"
        elif exp > 0:
            exp_clause = f"{_years_months_str(exp)} of experience on record"
        else:
            exp_clause = "experience data not available from CV"

        # Compose by verdict tier
        if v == "Strong Match":
            return (
                f"{rank_phrase} — {v.lower()} ({pct}); "
                f"{skill_clause} with {exp_clause}."
            )
        if v == "Good Match":
            return (
                f"{rank_phrase} — {v.lower()} ({pct}); "
                f"{skill_clause}. "
                f"Solid candidate with {exp_clause}."
            )
        if v == "Partial Match":
            missing_count = len(r.missing_skills)
            gap_note = (
                f"{missing_count} skill gap{'s' if missing_count != 1 else ''} identified"
                if missing_count > 0
                else "some alignment gaps noted"
            )
            return (
                f"{rank_phrase} — {v.lower()} ({pct}); "
                f"{gap_note}. Manual review recommended."
            )
        # Weak Match
        return (
            f"{rank_phrase} — {v.lower()} ({pct}); "
            f"significant gaps relative to the job requirements."
        )

    # ──────────────────────────────────────────────────────────────────────
    # Score breakdown notes
    # ──────────────────────────────────────────────────────────────────────

    def semantic_note(self, ctx: CandidateContext) -> str:
        """Generate a contextual note for the semantic similarity score.

        Args:
            ctx: Merged candidate context.

        Returns:
            A one-sentence interpretation of the semantic score.
        """
        s = ctx.ranking.semantic_score
        if s >= 0.85:
            return "CV content is an exceptionally close match to the job description language."
        if s >= LABEL_EXCELLENT_THRESHOLD:
            return "CV content closely mirrors the themes and terminology of the job description."
        if s >= LABEL_GOOD_THRESHOLD:
            return "CV content shows good topical overlap with the job description."
        if s >= LABEL_FAIR_THRESHOLD:
            return (
                "CV content partially overlaps with the job description; "
                "some areas of the role may not be addressed."
            )
        return (
            "CV content shows limited alignment with the job description; "
            "the candidate's background may be in a different domain."
        )

    def keyword_note(self, ctx: CandidateContext) -> str:
        """Generate a contextual note for the keyword match score.

        Args:
            ctx: Merged candidate context.

        Returns:
            A one-sentence interpretation of the keyword score.
        """
        r       = ctx.ranking
        matched = len(r.matched_skills)
        total   = r.jd_skill_count

        if total == 0:
            return "No specific skills were extracted from the job description."

        if matched == total:
            return f"All {total} required skills are present in the candidate's profile."
        if r.keyword_score >= 0.80:
            return (
                f"Strong skill coverage — {matched} of {total} required skills matched, "
                f"with only minor gaps."
            )
        if r.keyword_score >= LABEL_GOOD_THRESHOLD:
            return f"Good skill coverage — {matched} of {total} required skills matched."
        if r.keyword_score >= LABEL_FAIR_THRESHOLD:
            return (
                f"Partial skill coverage — {matched} of {total} required skills matched; "
                f"notable gaps remain."
            )
        return (
            f"Limited skill overlap — only {matched} of {total} required skills found; "
            f"significant upskilling may be needed."
        )

    def quality_note(self, ctx: CandidateContext) -> str:
        """Generate a contextual note for the CV quality score.

        Args:
            ctx: Merged candidate context.

        Returns:
            A one-sentence interpretation of the quality score.
        """
        q = ctx.ranking.quality_score
        if q >= 0.90:
            return (
                "CV is exceptionally well-structured with all key sections "
                "present and detailed."
            )
        if q >= LABEL_EXCELLENT_THRESHOLD:
            return "CV is well-structured and comprehensive, covering all major sections."
        if q >= LABEL_GOOD_THRESHOLD:
            return "CV is reasonably complete; most key sections are present."
        if q >= LABEL_FAIR_THRESHOLD:
            return (
                "CV has adequate structure but some sections are sparse or missing."
            )
        return (
            "CV appears incomplete — several key sections are absent or "
            "contain minimal information."
        )

    # ──────────────────────────────────────────────────────────────────────
    # Skills summary
    # ──────────────────────────────────────────────────────────────────────

    def skills_summary(self, ctx: CandidateContext) -> str:
        """Generate a plain-English skills summary sentence.

        Args:
            ctx: Merged candidate context.

        Returns:
            A concise summary of skill match status.
        """
        r       = ctx.ranking
        matched = len(r.matched_skills)
        total   = r.jd_skill_count
        missing = list(r.missing_skills)

        if total == 0:
            return "No specific skills were extracted from the job description to compare against."

        if matched == total:
            return (
                f"Candidate demonstrates all {total} skills identified in the job description."
            )

        missing_preview = missing[:3]
        suffix = (
            f", {len(missing) - 3} more"
            if len(missing) > 3
            else ""
        )
        missing_str = (
            ", ".join(missing_preview) + suffix
            if missing_preview
            else "none"
        )

        return (
            f"Candidate has {matched} of {total} required skill{'s' if total != 1 else ''}. "
            f"Missing: {missing_str}."
        )

    # ──────────────────────────────────────────────────────────────────────
    # Experience summary
    # ──────────────────────────────────────────────────────────────────────

    def experience_summary(self, ctx: CandidateContext) -> str:
        """Generate a plain-English experience summary sentence.

        Args:
            ctx: Merged candidate context.

        Returns:
            A natural summary of the candidate's experience level.
        """
        p     = ctx.parsed
        total = p.total_experience_months

        if not p.available:
            return "Detailed experience data is unavailable (parsed CV not found)."

        if total <= 0:
            if not p.roles:
                return "No experience entries could be extracted from this CV."
            return "Experience section is present but duration data could not be determined."

        role_count  = len(p.roles)
        dur_str     = _years_months_str(total)
        role_phrase = f"across {role_count} role{'s' if role_count != 1 else ''}"

        if total >= STRENGTH_SENIOR_MONTHS:
            return (
                f"Experienced professional with {dur_str} on record {role_phrase}."
            )
        if total >= STRENGTH_EXPERIENCE_MONTHS:
            return (
                f"{dur_str.capitalize()} of professional experience recorded {role_phrase}."
            )
        if total >= 6:
            return (
                f"{dur_str.capitalize()} of experience recorded {role_phrase}; "
                f"relatively early-career profile."
            )
        return (
            f"Only {dur_str} of experience recorded. "
            f"Candidate appears to be in the early stages of their career."
        )

    # ──────────────────────────────────────────────────────────────────────
    # Education summary
    # ──────────────────────────────────────────────────────────────────────

    def education_summary(self, ctx: CandidateContext) -> str:
        """Generate a plain-English education summary sentence.

        Args:
            ctx: Merged candidate context.

        Returns:
            A natural summary of the candidate's highest qualification.
        """
        if not ctx.parsed.available:
            return "Education data is unavailable (parsed CV not found)."
        if not ctx.parsed.education:
            return "No education entries could be extracted from this CV."

        level, field = _highest_education(ctx.parsed.education)

        if level and field:
            return f"{level} in {field}."
        if level:
            return f"Highest recorded qualification: {level}."
        if field:
            return f"Degree in {field} (level not specified)."
        return "Education section present but qualification details could not be determined."

    # ──────────────────────────────────────────────────────────────────────
    # Strengths detection
    # ──────────────────────────────────────────────────────────────────────

    def strengths(self, ctx: CandidateContext) -> List[str]:
        """Generate a list of concrete strength statements for this candidate.

        Each statement is triggered by a specific threshold crossing so that
        every bullet is factually defensible — not generic praise.

        Args:
            ctx: Merged candidate context.

        Returns:
            A list of strength strings (may be empty for very weak candidates).
        """
        r          = ctx.ranking
        p          = ctx.parsed
        result: List[str] = []

        # ── Complete skill match ──────────────────────────────────────────
        if r.jd_skill_count > 0 and len(r.missing_skills) == 0:
            result.append(
                f"Complete skill match — all {r.jd_skill_count} required skills are present."
            )
        elif r.keyword_score >= STRENGTH_KEYWORD_THRESHOLD:
            pct_str = _pct(r.keyword_score)
            result.append(
                f"Strong skill alignment — {pct_str} of required skills matched "
                f"({len(r.matched_skills)} of {r.jd_skill_count})."
            )

        # ── Semantic alignment ────────────────────────────────────────────
        if r.semantic_score >= STRENGTH_SEMANTIC_THRESHOLD:
            result.append(
                "High semantic relevance — the CV's content language closely "
                "reflects the job description's requirements and domain."
            )

        # ── Experience depth ──────────────────────────────────────────────
        if p.available and p.total_experience_months >= STRENGTH_SENIOR_MONTHS:
            yrs = p.total_experience_months // 12
            result.append(
                f"Seasoned professional with over {yrs} years of experience, "
                f"suggesting deep domain knowledge."
            )
        elif p.available and p.total_experience_months >= STRENGTH_EXPERIENCE_MONTHS:
            dur = _years_months_str(p.total_experience_months)
            result.append(
                f"Solid professional track record — {dur} of experience on record."
            )

        # ── CV quality ────────────────────────────────────────────────────
        if r.quality_score >= STRENGTH_QUALITY_THRESHOLD:
            result.append(
                "Well-structured, comprehensive CV — indicates strong attention "
                "to detail and professional communication."
            )

        # ── Advanced education ────────────────────────────────────────────
        if p.available and p.education:
            level, _ = _highest_education(p.education)
            if level in ADVANCED_DEGREE_LEVELS:
                result.append(
                    f"Advanced academic qualification ({level}) — demonstrates "
                    f"strong theoretical foundation."
                )

        # ── Certifications ────────────────────────────────────────────────
        if p.available and p.certifications:
            n_certs = len(p.certifications)
            cert_label = (
                p.certifications[0]
                if n_certs == 1
                else f"{n_certs} professional certifications"
            )
            result.append(
                f"Holds {cert_label}, reflecting continued professional development."
            )

        # ── Multilingual ──────────────────────────────────────────────────
        if p.available and len(p.languages) >= 2:
            lang_str = " and ".join(p.languages[:2])
            result.append(
                f"Multilingual proficiency ({lang_str}"
                + (f" and {len(p.languages) - 2} more" if len(p.languages) > 2 else "")
                + ") — an asset for diverse team environments."
            )

        return result

    # ──────────────────────────────────────────────────────────────────────
    # Gaps detection
    # ──────────────────────────────────────────────────────────────────────

    def gaps(self, ctx: CandidateContext) -> List[str]:
        """Generate a list of concrete gap statements for this candidate.

        Gaps are presented constructively — each bullet identifies a specific
        deficiency without language that could introduce bias.

        Args:
            ctx: Merged candidate context.

        Returns:
            A list of gap strings (empty for very strong candidates).
        """
        r          = ctx.ranking
        p          = ctx.parsed
        result: List[str] = []

        # ── Individual missing skills (capped) ────────────────────────────
        missing = list(r.missing_skills)
        shown   = missing[:GAP_MAX_SKILL_ITEMS]
        for skill in shown:
            result.append(
                f"Missing '{skill}' — identified as a required skill in the job description."
            )
        overflow = len(missing) - GAP_MAX_SKILL_ITEMS
        if overflow > 0:
            result.append(
                f"…and {overflow} additional required skill{'s' if overflow != 1 else ''} "
                f"not found in this CV."
            )

        # ── Low overall keyword coverage ──────────────────────────────────
        # Only add if we didn't already enumerate individual skills above
        if not missing and r.keyword_score < GAP_LOW_KEYWORD_THRESHOLD:
            result.append(
                f"Low overall skill overlap with the job description "
                f"({_pct(r.keyword_score)} match rate). "
                f"This may indicate a domain mismatch."
            )

        # ── Limited experience ────────────────────────────────────────────
        if p.available and 0 < p.total_experience_months < GAP_LIMITED_EXPERIENCE_MONTHS:
            dur = _years_months_str(p.total_experience_months)
            result.append(
                f"Limited professional experience on record ({dur}). "
                f"Role may require a more established track record."
            )
        elif p.available and p.total_experience_months == 0 and not p.roles:
            result.append(
                "No professional experience entries could be extracted from this CV."
            )

        # ── CV quality concern ────────────────────────────────────────────
        if r.quality_score < GAP_LOW_QUALITY_THRESHOLD:
            result.append(
                f"CV completeness score is low ({_pct(r.quality_score)}). "
                f"Key sections may be absent or underspecified — "
                f"candidate may benefit from being asked to resubmit a fuller CV."
            )

        return result

    # ──────────────────────────────────────────────────────────────────────
    # Recommendation
    # ──────────────────────────────────────────────────────────────────────

    def recommendation(self, ctx: CandidateContext) -> str:
        """Generate a concrete, actionable recommendation for the hiring manager.

        The recommendation is calibrated to the verdict tier and references
        specific missing skills, experience level, and quality signals.

        Args:
            ctx: Merged candidate context.

        Returns:
            A 1–3 sentence recommendation string.
        """
        r       = ctx.ranking
        p       = ctx.parsed
        v       = _verdict(r.final_score)
        missing = list(r.missing_skills)
        top_gap = missing[0] if missing else None
        top3    = ", ".join(missing[:3]) if missing else None

        # ── Build experience context phrase ───────────────────────────────
        if p.available and p.total_experience_months >= STRENGTH_EXPERIENCE_MONTHS:
            exp_note = (
                f" The candidate's {_years_months_str(p.total_experience_months)} "
                f"of experience is a positive signal."
            )
        elif p.available and 0 < p.total_experience_months < STRENGTH_EXPERIENCE_MONTHS:
            exp_note = (
                f" Note the relatively limited experience "
                f"({_years_months_str(p.total_experience_months)})."
            )
        else:
            exp_note = ""

        # ── Compose by verdict ────────────────────────────────────────────
        if v == "Strong Match":
            if not missing:
                return (
                    "Recommended for interview — candidate meets all evaluated criteria. "
                    "Proceed to the technical assessment stage."
                    + exp_note
                )
            probe = f"Consider probing depth of knowledge in {top_gap} during the interview."
            return (
                f"Recommended for interview.{exp_note} "
                f"Strong overall fit for this role. {probe}"
            )

        if v == "Good Match":
            if not missing:
                return (
                    "Consider for interview. Good overall alignment with the role."
                    + exp_note
                    + " No skill gaps identified — verify domain depth during screening."
                )
            gaps_str = ", ".join(missing[:2])
            return (
                f"Consider for interview.{exp_note} "
                f"Good overall fit; however, the candidate may need support with "
                f"{gaps_str}. "
                f"Clarify these areas during the screening call."
            )

        if v == "Partial Match":
            if top3:
                return (
                    f"Manual review recommended.{exp_note} "
                    f"The candidate shows potential but has notable gaps in: {top3}. "
                    f"Proceed only if these skills can be developed on the job or "
                    f"if other compensating factors are present."
                )
            return (
                "Manual review recommended. Some alignment gaps are noted. "
                "Consider whether the candidate's profile fits an alternative role."
                + exp_note
            )

        # Weak Match
        if top3:
            return (
                f"Not recommended at this stage. "
                f"Significant skill gaps: {top3}."
                + exp_note
                + " Candidate may be better suited to a more junior position "
                + "or a different specialisation."
            )
        return (
            "Not recommended at this stage. "
            "The candidate's profile does not adequately match the job requirements."
            + exp_note
        )


# ══════════════════════════════════════════════════════════════════════════
# Parsed-JSON loader
# ══════════════════════════════════════════════════════════════════════════

def _load_parsed_context(parsed_dir: str, candidate_id: str) -> ParsedContext:
    """Load and validate the module0b parsed JSON for one candidate.

    Args:
        parsed_dir:   Path to the directory containing parsed JSON files.
        candidate_id: Candidate identifier (e.g. 'Candidate_01').

    Returns:
        A populated ParsedContext if the file exists and is valid,
        otherwise ParsedContext.unavailable() with a logged warning.
    """
    path = os.path.join(parsed_dir, f"{candidate_id}.json")
    if not os.path.isfile(path):
        logger.warning(
            "Parsed JSON not found for %s — explanation will be generated "
            "from ranking signals only (path: %s).",
            candidate_id, path,
        )
        return ParsedContext.unavailable()

    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except json.JSONDecodeError as exc:
        logger.error(
            "Parsed JSON for %s is malformed: %s. "
            "Proceeding with ranking signals only.",
            candidate_id, exc,
        )
        return ParsedContext.unavailable()
    except OSError as exc:
        logger.error(
            "Could not read parsed JSON for %s: %s. "
            "Proceeding with ranking signals only.",
            candidate_id, exc,
        )
        return ParsedContext.unavailable()

    try:
        return ParsedContext.from_dict(data)
    except Exception as exc:   # guard against unexpected schema drift
        logger.error(
            "Unexpected error constructing ParsedContext for %s: %s. "
            "Proceeding with ranking signals only.",
            candidate_id, exc,
        )
        return ParsedContext.unavailable()


# ══════════════════════════════════════════════════════════════════════════
# Explanation builder
# ══════════════════════════════════════════════════════════════════════════

class ExplanationBuilder:
    """Assembles the full explanation JSON structure for one candidate.

    Delegates all text generation to TextGenerator and structures the
    results according to the canonical output schema.

    Attributes:
        _gen: The TextGenerator instance used for all NL generation.
    """

    def __init__(self) -> None:
        """Initialise the builder with its text generator."""
        self._gen: TextGenerator = TextGenerator()

    def build(self, ctx: CandidateContext) -> Dict[str, Any]:
        """Build the complete explanation dict for one candidate.

        Args:
            ctx: Complete merged context for the candidate.

        Returns:
            A dict matching the canonical explanation JSON schema.
        """
        r     = ctx.ranking
        p     = ctx.parsed
        gen   = self._gen

        v              = _verdict(r.final_score)
        headline_text  = gen.headline(ctx)
        exp_months     = p.total_experience_months if p.available else 0
        level, field   = (_highest_education(p.education) if p.available else ("", ""))
        matched_count  = len(r.matched_skills)
        total_skills   = r.jd_skill_count

        # ── Score breakdown ───────────────────────────────────────────────
        score_breakdown: Dict[str, Any] = {
            "semantic_score": {
                "value": round(r.semantic_score, 4),
                "label": _score_label(r.semantic_score),
                "note":  gen.semantic_note(ctx),
            },
            "keyword_score": {
                "value": round(r.keyword_score, 4),
                "label": _score_label(r.keyword_score),
                "note":  gen.keyword_note(ctx),
            },
            "quality_score": {
                "value": round(r.quality_score, 4),
                "label": _score_label(r.quality_score),
                "note":  gen.quality_note(ctx),
            },
            "final_score": {
                "value": round(r.final_score, 4),
                "label": v,
            },
        }

        # ── Skills block ──────────────────────────────────────────────────
        match_rate = (
            _pct(r.keyword_score)
            if total_skills > 0
            else "N/A"
        )
        skills_block: Dict[str, Any] = {
            "matched":    list(r.matched_skills),
            "missing":    list(r.missing_skills),
            "match_rate": match_rate,
            "summary":    gen.skills_summary(ctx),
        }

        # ── Experience block ──────────────────────────────────────────────
        experience_block: Dict[str, Any] = {
            "total_months":      exp_months,
            "total_years":       str(round(exp_months / 12, 1)) if exp_months > 0 else "0",
            "roles_detected":    len(p.roles) if p.available else 0,
            "parse_data_available": p.available,
            "summary":           gen.experience_summary(ctx),
        }
        if not p.available:
            experience_block["note"] = "Detailed experience data unavailable — parsed CV not found."

        # ── Education block ───────────────────────────────────────────────
        education_block: Dict[str, Any] = {
            "highest_level":        level or None,
            "field":                field or None,
            "entries_detected":     len(p.education) if p.available else 0,
            "parse_data_available": p.available,
            "summary":              gen.education_summary(ctx),
        }
        if not p.available:
            education_block["note"] = "Detailed education data unavailable — parsed CV not found."

        # ── Certifications block ──────────────────────────────────────────
        certifications_block: Dict[str, Any] = {
            "count":   len(p.certifications) if p.available else 0,
            "entries": p.certifications if p.available else [],
        }

        # ── Strengths / Gaps / Recommendation ─────────────────────────────
        strengths_list     = gen.strengths(ctx)
        gaps_list          = gen.gaps(ctx)
        recommendation_txt = gen.recommendation(ctx)

        # ── Assemble ──────────────────────────────────────────────────────
        return {
            "candidate_id":  r.candidate_id,
            "rank":          r.rank,
            "n_candidates":  ctx.n_candidates,
            "final_score":   round(r.final_score, 4),
            "verdict":       v,
            "headline":      headline_text,
            "data_sources":  {
                "ranking_details_available": True,
                "parsed_json_available":     p.available,
                "parse_warnings_count":      len(p.parse_warnings) if p.available else 0,
            },
            "explanation": {
                "score_breakdown": score_breakdown,
                "skills":          skills_block,
                "experience":      experience_block,
                "education":       education_block,
                "certifications":  certifications_block,
                "strengths":       strengths_list,
                "gaps":            gaps_list,
                "recommendation":  recommendation_txt,
            },
            "generated_at": datetime.now().strftime(ISO_FMT),
        }


# ══════════════════════════════════════════════════════════════════════════
# Report writer
# ══════════════════════════════════════════════════════════════════════════

class ReportWriter:
    """Handles all file I/O for the explainability engine.

    Writes individual JSON explanation files and the aggregate plain-text
    summary report.  All write operations are individually guarded with
    try/except so that one failure never prevents other files being written.
    """

    # ──────────────────────────────────────────────────────────────────────
    # Individual JSON
    # ──────────────────────────────────────────────────────────────────────

    def write_explanation_json(
        self,
        explanation: Dict[str, Any],
        output_dir:  str,
    ) -> bool:
        """Write one candidate's explanation dict as a formatted JSON file.

        Args:
            explanation: The assembled explanation dict from ExplanationBuilder.
            output_dir:  Directory to write the file into.

        Returns:
            True on success, False on any I/O error.
        """
        cid  = explanation["candidate_id"]
        path = os.path.join(output_dir, f"{cid}.json")
        try:
            with open(path, "w", encoding="utf-8") as fh:
                json.dump(explanation, fh, indent=2, ensure_ascii=False)
            logger.debug("Wrote explanation JSON → %s", path)
            return True
        except OSError as exc:
            logger.error("Failed to write explanation JSON for %s: %s", cid, exc)
            return False

    # ──────────────────────────────────────────────────────────────────────
    # Summary report
    # ──────────────────────────────────────────────────────────────────────

    def write_summary_report(
        self,
        explanations: List[Dict[str, Any]],
        output_dir:   str,
        jd_skill_count: int,
    ) -> bool:
        """Write the aggregate plain-text summary report for all candidates.

        The report is structured into three parts:
          1. Header — run metadata and overall statistics
          2. Ranked table — one row per candidate with key scores
          3. Per-candidate sections — full plain-English explanation

        Args:
            explanations:   List of assembled explanation dicts, sorted by rank.
            output_dir:     Directory to write summary_report.txt into.
            jd_skill_count: Number of skills extracted from the JD (for header).

        Returns:
            True on success, False on any I/O error.
        """
        lines = self._build_report_lines(explanations, jd_skill_count)
        path  = os.path.join(output_dir, SUMMARY_FILENAME)
        try:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write("\n".join(lines))
            logger.info("Summary report saved → %s", path)
            return True
        except OSError as exc:
            logger.error("Failed to write summary report: %s", exc)
            return False

    def _build_report_lines(
        self,
        explanations:   List[Dict[str, Any]],
        jd_skill_count: int,
    ) -> List[str]:
        """Build the list of text lines that make up the summary report.

        Args:
            explanations:   Sorted list of explanation dicts.
            jd_skill_count: Number of JD skills (for header context).

        Returns:
            List of string lines (no trailing newline on each).
        """
        W    = REPORT_WIDTH
        sep  = "═" * W
        thin = "─" * W
        now  = datetime.now().strftime(HUMAN_DATE_FMT)

        n_candidates  = len(explanations)
        n_recommended = sum(
            1 for e in explanations
            if e["verdict"] in {"Strong Match", "Good Match"}
        )
        n_strong      = sum(1 for e in explanations if e["verdict"] == "Strong Match")
        avg_score     = (
            sum(e["final_score"] for e in explanations) / n_candidates
            if n_candidates > 0
            else 0.0
        )

        lines: List[str] = []

        # ── Header ────────────────────────────────────────────────────────
        lines += [
            sep,
            _centre("BIAS-FREE HIRING PIPELINE", W),
            _centre("CANDIDATE EXPLAINABILITY REPORT", W),
            sep,
            f"  Generated      : {now}",
            f"  Candidates     : {n_candidates}",
            f"  JD Skill Count : {jd_skill_count}",
            f"  Average Score  : {_pct(avg_score)}",
            f"  Recommended    : {n_recommended} of {n_candidates} "
            f"(Strong: {n_strong})",
            sep,
            "",
        ]

        # ── Ranked table ──────────────────────────────────────────────────
        lines.append(_centre("RANKED OVERVIEW", W))
        lines.append(thin)

        # Table header
        col_rank    = 4
        col_cand    = 22
        col_score   = 7
        col_sem     = 8
        col_kw      = 7
        col_qual    = 7
        col_verdict = 15
        col_matched = 9

        header = (
            f"  {'Rank':<{col_rank}} "
            f"{'Candidate':<{col_cand}} "
            f"{'Score':>{col_score}} "
            f"{'Semantic':>{col_sem}} "
            f"{'Keyword':>{col_kw}} "
            f"{'Quality':>{col_qual}} "
            f"{'Verdict':<{col_verdict}} "
            f"{'Skills':>{col_matched}}"
        )
        subline = (
            f"  {'-'*col_rank} "
            f"{'-'*col_cand} "
            f"{'-'*col_score} "
            f"{'-'*col_sem} "
            f"{'-'*col_kw} "
            f"{'-'*col_qual} "
            f"{'-'*col_verdict} "
            f"{'-'*col_matched}"
        )
        lines += [header, subline]

        for e in explanations:
            bd         = e["explanation"]["score_breakdown"]
            sk         = e["explanation"]["skills"]
            matched_n  = len(e["explanation"]["skills"]["matched"])
            total_n    = e["explanation"]["score_breakdown"]["keyword_score"].get(
                "note", ""  # not the right field, use jd_skill_count approach
            )
            # Recover jd_skill_count from the candidate's own data:
            # matched / match_rate
            mr_str     = sk.get("match_rate", "N/A")
            skill_str  = f"{matched_n}/{jd_skill_count}" if jd_skill_count > 0 else f"{matched_n}/??"

            row = (
                f"  {e['rank']:<{col_rank}} "
                f"{e['candidate_id']:<{col_cand}} "
                f"{_pct(e['final_score']):>{col_score}} "
                f"{_pct(bd['semantic_score']['value']):>{col_sem}} "
                f"{_pct(bd['keyword_score']['value']):>{col_kw}} "
                f"{_pct(bd['quality_score']['value']):>{col_qual}} "
                f"{e['verdict']:<{col_verdict}} "
                f"{skill_str:>{col_matched}}"
            )
            lines.append(row)

        lines += ["", thin, ""]

        # ── Per-candidate narrative ────────────────────────────────────────
        lines.append(_centre("CANDIDATE DETAIL", W))
        lines.append("")

        for e in explanations:
            cid      = e["candidate_id"]
            exp_sec  = e["explanation"]
            rank     = e["rank"]
            verdict  = e["verdict"]
            ds       = e.get("data_sources", {})

            lines += [
                thin,
                f"  #{rank}  {cid}  |  {verdict}  |  Final Score: {_pct(e['final_score'])}",
                thin,
            ]

            # Data availability notice
            if not ds.get("parsed_json_available", True):
                lines.append(
                    "  [!] Parsed CV data was unavailable for this candidate. "
                    "Explanation is based on ranking signals only."
                )
                lines.append("")

            # Headline
            lines.append(f"  {e['headline']}")
            lines.append("")

            # Score breakdown
            lines.append("  SCORE BREAKDOWN")
            bd = exp_sec["score_breakdown"]
            for key, label in [
                ("final_score",    "Final"),
                ("semantic_score", "Semantic"),
                ("keyword_score",  "Keyword"),
                ("quality_score",  "Quality"),
            ]:
                entry = bd[key]
                bar   = _mini_bar(entry["value"])
                note  = entry.get("note", "")
                lines.append(
                    f"    {label:<10}  {_pct(entry['value']):>5}  [{bar}]  {entry['label']}"
                )
                if note:
                    lines.append(f"             {_wrap_indent(note, width=W - 14, indent=13)}")
            lines.append("")

            # Skills
            sk = exp_sec["skills"]
            lines.append("  SKILLS")
            lines.append(f"    {sk['summary']}")
            if sk["matched"]:
                lines.append(
                    f"    Matched : {', '.join(sk['matched'])}"
                )
            if sk["missing"]:
                lines.append(
                    f"    Missing : {', '.join(sk['missing'])}"
                )
            lines.append("")

            # Experience & Education
            lines.append("  EXPERIENCE")
            lines.append(f"    {exp_sec['experience']['summary']}")
            lines.append("")
            lines.append("  EDUCATION")
            lines.append(f"    {exp_sec['education']['summary']}")
            lines.append("")

            # Strengths
            if exp_sec["strengths"]:
                lines.append("  STRENGTHS")
                for s in exp_sec["strengths"]:
                    for part in _wrap_bullet(s, width=W - 8, prefix="    ✓ "):
                        lines.append(part)
                lines.append("")

            # Gaps
            if exp_sec["gaps"]:
                lines.append("  GAPS")
                for g in exp_sec["gaps"]:
                    for part in _wrap_bullet(g, width=W - 8, prefix="    ✗ "):
                        lines.append(part)
                lines.append("")

            # Recommendation
            lines.append("  RECOMMENDATION")
            for part in textwrap.wrap(
                exp_sec["recommendation"],
                width=W - 6,
                initial_indent="    ",
                subsequent_indent="    ",
            ):
                lines.append(part)
            lines.append("")

        # ── Footer ────────────────────────────────────────────────────────
        lines += [
            sep,
            _centre("PIPELINE STATISTICS", W),
            sep,
            f"  Total candidates  : {n_candidates}",
            f"  Strong Match      : {sum(1 for e in explanations if e['verdict'] == 'Strong Match')}",
            f"  Good Match        : {sum(1 for e in explanations if e['verdict'] == 'Good Match')}",
            f"  Partial Match     : {sum(1 for e in explanations if e['verdict'] == 'Partial Match')}",
            f"  Weak Match        : {sum(1 for e in explanations if e['verdict'] == 'Weak Match')}",
            f"  Average score     : {_pct(avg_score)}",
            f"  Recommended       : {n_recommended} ({_pct(n_recommended / n_candidates) if n_candidates else '0%'})",
            "",
            "  This report was generated automatically by the Bias-Free Hiring",
            "  Pipeline. All candidate identifiers are anonymized (module0).",
            "  Scores reflect algorithmic signals only and must be reviewed by",
            "  a qualified human decision-maker before any hiring action is taken.",
            sep,
            _centre("END OF REPORT", W),
            sep,
            "",
        ]

        return lines


# ══════════════════════════════════════════════════════════════════════════
# Formatting helpers (module-private)
# ══════════════════════════════════════════════════════════════════════════

def _centre(text: str, width: int) -> str:
    """Centre-pad a string to a given width with surrounding spaces.

    Args:
        text:  The string to centre.
        width: Total line width.

    Returns:
        Centred string.
    """
    return text.center(width)


def _mini_bar(score: float, length: int = 20) -> str:
    """Render a compact ASCII progress bar for a 0–1 score.

    Args:
        score:  Value between 0.0 and 1.0.
        length: Total number of characters in the bar.

    Returns:
        A string of filled ('█') and empty ('░') block characters.
    """
    filled = round(score * length)
    return "█" * filled + "░" * (length - filled)


def _wrap_indent(text: str, width: int, indent: int) -> str:
    """Wrap text to *width* columns with a hanging indent of *indent* spaces.

    Args:
        text:   The text to wrap.
        width:  Maximum line width.
        indent: Number of spaces on subsequent lines.

    Returns:
        The wrapped text as a single string (may contain embedded newlines).
    """
    wrapped = textwrap.fill(
        text,
        width=width,
        subsequent_indent=" " * indent,
    )
    return wrapped


def _wrap_bullet(text: str, width: int, prefix: str) -> List[str]:
    """Wrap a bullet point item, aligning continuation lines with the text.

    Args:
        text:   The bullet text (without the prefix).
        width:  Maximum line width (including the prefix).
        prefix: The bullet prefix string (e.g. '    ✓ ').

    Returns:
        List of strings; first item has the prefix, subsequent items are
        indented to align with the text start.
    """
    hanging = " " * len(prefix)
    wrapped = textwrap.wrap(
        text,
        width=width,
        initial_indent=prefix,
        subsequent_indent=hanging,
    )
    return wrapped if wrapped else [prefix + text]


# ══════════════════════════════════════════════════════════════════════════
# Explainability Engine — main orchestration class
# ══════════════════════════════════════════════════════════════════════════

class ExplainabilityEngine:
    """Orchestrates the full explainability stage for all ranked candidates.

    This class is the single entry point for all explanation generation.  It
    delegates to ExplanationBuilder for per-candidate logic and to
    ReportWriter for I/O, keeping orchestration cleanly separated from
    business logic.

    Attributes:
        _builder: Shared ExplanationBuilder instance.
        _writer:  Shared ReportWriter instance.
    """

    def __init__(self) -> None:
        """Initialise the engine with its builder and writer dependencies."""
        self._builder: ExplanationBuilder = ExplanationBuilder()
        self._writer:  ReportWriter       = ReportWriter()

    def explain(
        self,
        ranking_details: Dict[str, Dict[str, Any]],
        parsed_dir:      str,
        output_dir:      str,
    ) -> bool:
        """Generate all explanations and write output artefacts.

        For each candidate in *ranking_details*:
          1. Load enrichment data from *parsed_dir* (gracefully skipped if absent).
          2. Build the full explanation dict via ExplanationBuilder.
          3. Write individual JSON to *output_dir*.

        After all candidates are processed:
          4. Write the aggregate summary_report.txt.

        Args:
            ranking_details: The ``last_ranking_details`` dict from module1's
                             ScreenRanker, keyed by candidate_id.
            parsed_dir:      Path to the directory containing module0b parsed
                             JSON files.
            output_dir:      Destination directory for all output files.

        Returns:
            True if at least one explanation was written successfully,
            False if every candidate failed or *ranking_details* is empty.
        """
        if not ranking_details:
            logger.warning("ranking_details is empty — nothing to explain.")
            return False

        try:
            os.makedirs(output_dir, exist_ok=True)
        except OSError as exc:
            logger.error("Cannot create output directory '%s': %s", output_dir, exc)
            return False

        n_candidates    = len(ranking_details)
        jd_skill_count  = self._infer_jd_skill_count(ranking_details)
        explanations:   List[Dict[str, Any]] = []
        success_count:  int = 0

        # Sort processing order by rank so log output is naturally ordered.
        sorted_entries = sorted(
            ranking_details.items(),
            key=lambda kv: kv[1].get("rank", 999),
        )

        for candidate_id, raw_data in sorted_entries:
            logger.info(
                "Processing %s (rank %s of %d) …",
                candidate_id,
                raw_data.get("rank", "?"),
                n_candidates,
            )

            try:
                ranking_entry = RankingEntry.from_dict(candidate_id, raw_data)
            except Exception as exc:
                logger.error(
                    "Failed to parse ranking data for %s: %s — skipping.",
                    candidate_id, exc,
                )
                continue

            parsed_ctx = _load_parsed_context(parsed_dir, candidate_id)

            ctx = CandidateContext(
                ranking      = ranking_entry,
                parsed       = parsed_ctx,
                n_candidates = n_candidates,
            )

            try:
                explanation = self._builder.build(ctx)
            except Exception as exc:
                logger.error(
                    "Explanation builder failed for %s: %s — skipping.",
                    candidate_id, exc,
                )
                continue

            if self._writer.write_explanation_json(explanation, output_dir):
                success_count += 1
                explanations.append(explanation)
            else:
                # Writing failed but we still keep the dict for the summary
                explanations.append(explanation)

        if not explanations:
            logger.error("No explanations could be generated or written.")
            return False

        # Sort by rank for the summary report
        explanations.sort(key=lambda e: e.get("rank", 999))

        self._writer.write_summary_report(
            explanations    = explanations,
            output_dir      = output_dir,
            jd_skill_count  = jd_skill_count,
        )

        logger.info(
            "Explainability stage complete — %d/%d explanations written.",
            success_count, n_candidates,
        )

        return success_count > 0

    @staticmethod
    def _infer_jd_skill_count(ranking_details: Dict[str, Dict[str, Any]]) -> int:
        """Infer the JD skill count from any entry in ranking_details.

        All candidates share the same JD so any entry's jd_skill_count is
        representative.

        Args:
            ranking_details: The full ranking_details dict.

        Returns:
            The JD skill count, or 0 if it cannot be determined.
        """
        for data in ranking_details.values():
            count = data.get("jd_skill_count", 0)
            if count:
                return int(count)
        return 0


# ══════════════════════════════════════════════════════════════════════════
# Singleton engine helper
# ══════════════════════════════════════════════════════════════════════════

_engine_instance: Optional[ExplainabilityEngine] = None


def _get_engine() -> ExplainabilityEngine:
    """Return the module-level cached ExplainabilityEngine instance.

    Returns:
        The shared ExplainabilityEngine.
    """
    global _engine_instance
    if _engine_instance is None:
        _engine_instance = ExplainabilityEngine()
    return _engine_instance


# ══════════════════════════════════════════════════════════════════════════
# run() — primary programmatic entry point called by main.py
# ══════════════════════════════════════════════════════════════════════════

def run(
    ranking_details: Dict[str, Dict[str, Any]],
    parsed_dir:      str,
    output_dir:      str,
) -> bool:
    """Execute the full explainability stage.

    This function is the canonical entry point for programmatic callers
    (main.py).  It mirrors the ``run()`` convention established by
    module0 and module0b, providing a consistent pipeline interface.

    Args:
        ranking_details: The ``last_ranking_details`` dict from
                         module1.ScreenRanker.rank_candidates().
        parsed_dir:      Path to the directory of parsed JSON files
                         produced by module0b.
        output_dir:      Destination directory for explanation outputs.
                         Created automatically if it does not exist.

    Returns:
        True if at least one explanation file was written successfully.
        False if ranking_details is empty or all candidates failed.
    """
    import time

    print()
    print("=" * 60)
    print("  MODULE 2 — EXPLAINABILITY ENGINE")
    print("=" * 60)

    if not ranking_details:
        print("\n  [ERROR] ranking_details is empty.")
        print("          Ensure module1.run() completed successfully before this stage.")
        return False

    n = len(ranking_details)
    print(f"\n  Candidates   : {n}")
    print(f"  Parsed JSON  : {parsed_dir}")
    print(f"  Output       : {output_dir}")
    print()

    t0     = time.time()
    engine = _get_engine()
    ok     = engine.explain(
        ranking_details = ranking_details,
        parsed_dir      = parsed_dir,
        output_dir      = output_dir,
    )
    elapsed = time.time() - t0

    if ok:
        print(f"\n  [OK] Explanations generated in {elapsed:.1f}s")
        print(f"  Outputs → {output_dir}/")
        print(f"  Summary → {os.path.join(output_dir, SUMMARY_FILENAME)}")
    else:
        print("\n  [FAILED] Explainability stage could not generate any output.")
        print("           Check logs for details.")

    print("=" * 60)
    return ok


# ══════════════════════════════════════════════════════════════════════════
# Standalone CLI
# ══════════════════════════════════════════════════════════════════════════

def _build_arg_parser() -> argparse.ArgumentParser:
    """Build the argument parser for standalone execution.

    Returns:
        Configured ArgumentParser instance.
    """
    _base = os.path.dirname(os.path.abspath(__file__))

    p = argparse.ArgumentParser(
        prog="module2",
        description=(
            "Explainability Engine — Bias-Free Hiring Pipeline\n\n"
            "Reads ranking_details from a JSON file (exported from module1) "
            "and generates per-candidate explanation JSON files plus a "
            "consolidated summary report."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python module2.py --ranking-file ranking_details.json \\\n"
            "                    --parsed-dir parsed \\\n"
            "                    --output-dir explanations\n\n"
            "  # Export ranking_details from a live pipeline:\n"
            "  python -c \"\n"
            "    import json, module1\n"
            "    r = module1.load_ranker()\n"
            "    json.dump(r.last_ranking_details,\n"
            "              open('ranking_details.json','w'), indent=2)\n"
            "  \"\n"
        ),
    )
    p.add_argument(
        "--ranking-file",
        required=True,
        metavar="FILE",
        help=(
            "Path to a JSON file containing last_ranking_details "
            "(exported from module1.ScreenRanker.last_ranking_details)."
        ),
    )
    p.add_argument(
        "--parsed-dir",
        default=os.path.join(_base, "parsed"),
        metavar="DIR",
        help="Directory of parsed JSON files from module0b (default: parsed/).",
    )
    p.add_argument(
        "--output-dir",
        default=os.path.join(_base, OUTPUT_DIR_NAME),
        metavar="DIR",
        help=f"Destination directory for explanation outputs (default: {OUTPUT_DIR_NAME}/).",
    )
    p.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose/debug logging.",
    )
    return p


def _configure_logging(verbose: bool = False) -> None:
    """Configure the root logger for standalone execution.

    Args:
        verbose: If True, sets the log level to DEBUG; otherwise INFO.
    """
    logging.basicConfig(
        level   = logging.DEBUG if verbose else logging.INFO,
        format  = LOG_FORMAT,
        datefmt = DATE_FMT,
    )


if __name__ == "__main__":
    _args = _build_arg_parser().parse_args()
    _configure_logging(verbose=_args.verbose)

    # Load ranking_details from the supplied JSON file
    try:
        with open(_args.ranking_file, "r", encoding="utf-8") as _fh:
            _ranking_details: Dict[str, Dict[str, Any]] = json.load(_fh)
    except FileNotFoundError:
        logger.critical("Ranking file not found: %s", _args.ranking_file)
        sys.exit(1)
    except json.JSONDecodeError as _exc:
        logger.critical("Ranking file is not valid JSON: %s", _exc)
        sys.exit(1)
    except OSError as _exc:
        logger.critical("Cannot read ranking file: %s", _exc)
        sys.exit(1)

    _ok = run(
        ranking_details = _ranking_details,
        parsed_dir      = _args.parsed_dir,
        output_dir      = _args.output_dir,
    )
    sys.exit(0 if _ok else 1)